AllCops:
  Include:
    - Rakefile
    - config.ru
    - Gemfile
  Exclude:
    - bin/**
    - db/schema.rb
    - db/migrate/**
    - script/**
    - vendor/**/*
    - node_modules/**/*

Rails:
  Enabled: true

Documentation:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

AccessModifierIndentation:
  EnforcedStyle: outdent

IfUnlessModifier:
  Enabled: false

CaseIndentation:
  EnforcedStyle: case
  IndentOneStep: true

MethodLength:
  CountComments: false
  Max: 20

SignalException:
  Enabled: false

ColonMethodCall:
  Enabled: false

AsciiComments:
  Enabled: false

RegexpLiteral:
  Enabled: false

AssignmentInCondition:
  Enabled: false

ParameterLists:
  CountKeywordArgs: false

SingleLineBlockParams:
  Methods:
    - reduce:
        - memo
        - item

Metrics/AbcSize:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/ExtraSpacing:
  Enabled: true

Style/Lambda:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Performance/Sample:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%w': '()'
    '%i': '()'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
