plugins: rubocop-rails

AllCops:
  NewCops: enable
  Include:
    - Rakefile
    - config.ru
    - Gemfile
    - '**/*.rb'
  Exclude:
    - bin/**
    - db/schema.rb
    - db/migrate/**
    - script/**
    - vendor/**/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 200

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/CaseIndentation:
  EnforcedStyle: case
  IndentOneStep: true

Metrics/MethodLength:
  CountComments: false
  Max: 20

Style/SignalException:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/SingleLineBlockParams:
  Methods:
    - reduce:
        - memo
        - item

Metrics/AbcSize:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Sample:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%w': '()'
    '%i': '()'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Layout/EmptyLinesAfterModuleInclusion:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false
