<%= Rails.env %>:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  domain: <%= ENV['CANONICAL_HOST'] %>
  protocol: <%= ENV['CANONICAL_PROTOCOL'] || 'http' %>
  port: "<%= ENV['RACK_ENV'] == 'development' ? ENV['CANONICAL_PORT'] : nil %>"
  show_backtrace: <%= BooleanEnvironmentVariable.new(ENV['SHOW_BACKTRACE']).as_bool %>
  sentry_dsn: <%= ENV['SENTRY_DSN'] %>
  auth_username: <%= ENV['BASIC_AUTH_USERNAME'] %>
  auth_password: <%= ENV['BASIC_AUTH_PASSWORD'] %>
  mailer_from: <%= ENV['MAILER_FROM'] %>
  smtp_address: <%= ENV['SMTP_ADDRESS'] %>
  smtp_port: <%= ENV['SMTP_PORT'] %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  force_ssl: <%= BooleanEnvironmentVariable.new(ENV['FORCE_SSL']).as_bool %>
