name: CD

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'

jobs:
  docker-tag:
    runs-on: ubuntu-latest

    outputs:
      docker-tag: ${{steps.tag.outputs.tag}}

    steps:
      - uses: actions/checkout@v2

      - name: Set Docker tag
        id: tag
        run: |
          TAG=$(echo "${{github.ref}}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{github.ref}}" == "refs/tags/"* ]] && TAG=$(echo $TAG | sed -e 's/^v//')
          [ "$TAG" == "master" ] && TAG=latest
          TAG=latest
          echo "::set-output name=tag::$TAG"

  build-and-push:
    needs: docker-tag
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: ${{needs.docker-tag.outputs.docker-tag}}

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: make build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: mirego-builds
          password: ${{secrets.MIREGO_GITHUB_PACKAGES_ACCESS_TOKEN}}

      - name: Push Docker image
        run: make push
