name: CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  docker-tag:
    runs-on: ubuntu-24.04

    outputs:
      docker-tag: ${{steps.tag.outputs.tag}}

    steps:
      - uses: actions/checkout@v3

      - id: tag
        run: |
          TAG=$(echo "${{github.ref}}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{github.ref}}" == "refs/tags/"* ]] && TAG=$(echo $TAG | sed -e 's/^v//')
          [ "$TAG" == "main" ] && TAG=latest
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  build-and-push:
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: docker-tag
    runs-on: ubuntu-24.04
    env:
      DOCKER_TAG: ${{needs.docker-tag.outputs.docker-tag}}

    steps:
      - uses: actions/checkout@v2

      - run: make build

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: mirego-builds
          password: ${{secrets.MIREGO_GITHUB_PACKAGES_ACCESS_TOKEN}}

      - run: make push
