name: CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  docker-tag:
    runs-on: ubuntu-latest

    outputs:
      docker-tag: ${{steps.tag.outputs.tag}}

    steps:
      - uses: actions/checkout@v3

      - id: tag
        run: |
          TAG=$(echo "${{github.ref}}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{github.ref}}" == "refs/tags/"* ]] && TAG=$(echo $TAG | sed -e 's/^v//')
          [ "$TAG" == "main" ] && TAG=latest
          echo "::set-output name=tag::$TAG"

  build-and-push:
    needs: docker-tag
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: ${{needs.docker-tag.outputs.docker-tag}}

    steps:
      - uses: actions/checkout@v2

      - run: make build

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: mirego-builds
          password: ${{secrets.MIREGO_GITHUB_PACKAGES_ACCESS_TOKEN}}

      - run: make push
