name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:10.19
        env:
          POSTGRES_DB: killswitch_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      CANONICAL_HOST: localhost
      DATABASE_URL: postgres://postgres:postgres@localhost/killswitch_test
      MAILER_FROM: localhost
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: npm install
      - run: make lint
      - run: make test
      - run: make build
